from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0001_initial'; down_revision=None; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('entities', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('name', sa.String(200), nullable=False), sa.Column('jurisdiction', sa.String(100), nullable=False), sa.Column('entity_type', sa.String(30), nullable=False), sa.Column('parent_entity_id', sa.Integer(), sa.ForeignKey('entities.id', ondelete='SET NULL')), sa.Column('ownership_pct', sa.Numeric(7,4)), sa.Column('incorporation_date', sa.Date()), sa.Column('tax_id', sa.String(100)))
    op.create_index('ix_entities_name','entities',['name']); op.create_index('ix_entities_jurisdiction','entities',['jurisdiction']); op.create_index('ix_entities_entity_type','entities',['entity_type'])
    op.create_table('substance_records', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('entity_id', sa.Integer(), sa.ForeignKey('entities.id', ondelete='CASCADE'), nullable=False), sa.Column('period', sa.Date(), nullable=False), sa.Column('local_employee_count', sa.Integer(), nullable=False), sa.Column('has_local_office', sa.Boolean(), nullable=False), sa.Column('decision_evidence_notes', sa.Text()), sa.UniqueConstraint('entity_id','period',name='uq_substance_entity_period'))
    op.create_index('ix_substance_records_entity_id','substance_records',['entity_id']); op.create_index('ix_substance_records_period','substance_records',['period'])
    op.create_table('board_meetings', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('substance_record_id', sa.Integer(), sa.ForeignKey('substance_records.id', ondelete='CASCADE'), nullable=False), sa.Column('meeting_date', sa.Date(), nullable=False), sa.Column('location', sa.String(200), nullable=False), sa.Column('attendee_ids', postgresql.JSONB(), nullable=False))
    op.create_index('ix_board_meetings_substance_record_id','board_meetings',['substance_record_id'])
    op.create_table('intercompany_transactions', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('from_entity_id', sa.Integer(), sa.ForeignKey('entities.id', ondelete='RESTRICT'), nullable=False), sa.Column('to_entity_id', sa.Integer(), sa.ForeignKey('entities.id', ondelete='RESTRICT'), nullable=False), sa.Column('type', sa.String(30), nullable=False), sa.Column('amount', sa.Numeric(20,4), nullable=False), sa.Column('currency', sa.String(3), nullable=False), sa.Column('transaction_date', sa.Date(), nullable=False), sa.Column('stated_price', sa.Numeric(20,8), nullable=False), sa.Column('benchmark_low', sa.Numeric(20,8), nullable=False), sa.Column('benchmark_high', sa.Numeric(20,8), nullable=False), sa.Column('tp_documentation_link', sa.Text()))
    for name,col in [('ix_ic_from','from_entity_id'),('ix_ic_to','to_entity_id'),('ix_ic_type','type'),('ix_ic_date','transaction_date')]: op.create_index(name,'intercompany_transactions',[col])
    op.create_table('treaty_rates', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('country_from', sa.String(100), nullable=False), sa.Column('country_to', sa.String(100), nullable=False), sa.Column('income_type', sa.String(30), nullable=False), sa.Column('withholding_rate', sa.Numeric(7,4), nullable=False), sa.Column('treaty_source_url', sa.Text(), nullable=False), sa.Column('last_verified_date', sa.Date(), nullable=False))
    op.create_index('ix_treaty_rates_from','treaty_rates',['country_from']); op.create_index('ix_treaty_rates_to','treaty_rates',['country_to']); op.create_index('ix_treaty_rates_verified','treaty_rates',['last_verified_date'])
    op.create_table('pillar_two_status', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('entity_id', sa.Integer(), sa.ForeignKey('entities.id', ondelete='CASCADE'), nullable=False), sa.Column('jurisdiction', sa.String(100), nullable=False), sa.Column('period', sa.Date(), nullable=False), sa.Column('globe_income', sa.Numeric(20,4)), sa.Column('covered_taxes', sa.Numeric(20,4)), sa.Column('effective_tax_rate', sa.Numeric(7,4)), sa.Column('qdmtt_applicable', sa.Boolean(), nullable=False), sa.Column('safe_harbour_type', sa.String(50)), sa.Column('gir_filing_deadline', sa.Date()), sa.Column('gir_filed', sa.Boolean(), nullable=False), sa.UniqueConstraint('entity_id','period',name='uq_pillar_entity_period'))
    op.create_index('ix_pillar_entity','pillar_two_status',['entity_id']); op.create_index('ix_pillar_jurisdiction','pillar_two_status',['jurisdiction']); op.create_index('ix_pillar_period','pillar_two_status',['period'])
    op.create_table('compliance_calendar', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('entity_id', sa.Integer(), sa.ForeignKey('entities.id', ondelete='CASCADE'), nullable=False), sa.Column('obligation_type', sa.String(100), nullable=False), sa.Column('jurisdiction', sa.String(100), nullable=False), sa.Column('deadline', sa.Date(), nullable=False), sa.Column('status', sa.String(20), nullable=False))
    for name,col in [('ix_cc_entity','entity_id'),('ix_cc_obligation','obligation_type'),('ix_cc_jurisdiction','jurisdiction'),('ix_cc_deadline','deadline'),('ix_cc_status','status')]: op.create_index(name,'compliance_calendar',[col])
    op.create_table('audit_events', sa.Column('id', sa.Integer(), primary_key=True), sa.Column('actor', sa.String(200), nullable=False), sa.Column('action', sa.String(100), nullable=False), sa.Column('object_type', sa.String(100), nullable=False), sa.Column('object_id', sa.String(100), nullable=False), sa.Column('payload', postgresql.JSONB(), nullable=False), sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index('ix_audit_created','audit_events',['created_at'])

def downgrade():
    for t in ['audit_events','compliance_calendar','pillar_two_status','treaty_rates','intercompany_transactions','board_meetings','substance_records','entities']:
        op.drop_table(t)
